🎨 Improved logging and comparing mechanism
dyvenia/nesso-starter-project pull request #4
Opened 2023-06-23 09:57 UTC by djagoda881

The prefect_deployment script has been improved.

In the previous version, the script compared the branch from which the PR was created with the main branch. However, due to the lack of a trigger in GitHub Actions that allows running actions after a PR is accepted, a minor change in the script's functionality was necessary. The GitHub Action is now triggered after changes are pushed to the main branch (only after the PR is accepted), which will cause the previous version of the script to fail since it would compare the main branch with itself and not detect any changes. In the latest version of the script, it examines all commits included between the merge commit and the latest merge commit, allowing it to detect newly added deployments.

Additionally, the script has replaced print statements with logging, and a revert_string_list() function has been added to reverse the list of commits, ensuring that everything is executed in the correct order.

2023-06-23 10:51 UTC, Trymzet requested changes

2023-06-23 10:51 UTC, Trymzet commented on .github/scripts/prefect_deployments.py
> +def get_commits(current_branch: str) -> List[str]:
can be just `branch`?

2023-06-23 10:51 UTC, Trymzet commented on .github/scripts/prefect_deployments.py
> +    Retrieve the commit hashes of the parent commits involved in a given branch's merge.
Is this merge-specific, or is this function generic as the name says: `get_commits()`, meaning it basically gets all parent commits for a specified branch? I feel like either the func name is too generic or the docstring too specific.

2023-06-23 10:51 UTC, Trymzet commented on .github/scripts/prefect_deployments.py
> +    string_list[:] = string_list[::-1]
Is this really only for strings or does this work for any list? Maybe you can just use the builtin `reversed()` or `mylist.reverse()`?

2023-06-23 12:59 UTC, djagoda881 commented on .github/scripts/prefect_deployments.py
> +def get_commits(current_branch: str) -> List[str]:
[🎨 Imporved structure an docstrings](https://github.com/dyvenia/nesso-starter-project/pull/4/commits/8e8c4b3de2e9da331591f6d06429185987384bff)

2023-06-23 13:00 UTC, djagoda881 commented on .github/scripts/prefect_deployments.py
> +    Retrieve the commit hashes of the parent commits involved in a given branch's merge.
Yes, the docstrings were too specific and confusing. I corrected it [🎨 Imporved structure an docstrings](https://github.com/dyvenia/nesso-starter-project/pull/4/commits/8e8c4b3de2e9da331591f6d06429185987384bff)

2023-06-26 11:08 UTC, Trymzet approved these changes
Looks good

2023-06-26 11:10 UTC, merged